### ISSUE TITLE
数十件に一回本物の yude さんが発したことのあるツイートを紛れ込ませ、そのツイートに「ダウト」とリプライすると謎のご褒美がもらえる

### ISSUE THREAD

**Issue by ghost** [yuderobot/ai#4]
なお、謎のご褒美は世界に点在する謎のウェブサイトへのURLを所望する

**Comment by yude** [comment]
Currently working on this

**Comment by pepepper** [comment]
これマルコフ連鎖の出力の結果偶然元と同じ文章になったときどうするの・・・

**Comment by yude** [comment]
super extreme good question. i was going to implement this without considering about that.
```python
if sentence in tweets:
  do_something()
```

**Comment by ghost** [comment]
> これマルコフ連鎖の出力の結果偶然元と同じ文章になったときどうするの・・・

死……

**Comment by pepepper** [comment]
> > これマルコフ連鎖の出力の結果偶然元と同じ文章になったときどうするの・・・
> 
> 死……

そんな・・・

**Comment by yude** [comment]
Implemented in 876510d6adb6e185ce4775239507e87562cfed3d, 9c71da69d8b64fb7a966b5c4db9d6b49f3321303, f7b313a41b13fd577c8191a47bd88601ad9d3285.

**Comment by yude** [comment]
ご褒美が無いな

**Comment by ghost** [comment]
> Implemented in 876510d6adb6e185ce4775239507e87562cfed3d, 9c71da69d8b64fb7a966b5c4db9d6b49f3321303, f7b313a41b13fd577c8191a47bd88601ad9d3285.

マジか
